server:
#  端口号
  port: 9100

eureka:
  client:
    serviceUrl:
      #指定注册中心地址
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
#    服务名
    name: config-server
  cloud:
    config:
      server:
        #              配置 git 库信息
        git:
          uri: https://gitee.com/huguobn/gbhu-spring-boot-config.git
          timeout: 5
#          默认分支
#          default-label: master
#          公开库可以不用账号密码
#          username:
#          password: